version: '3'
services:
  ghost:
    container_name: ghost
    image: ghost:alpine
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      - server__host=0.0.0.0
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=root
      - database__connection__password=mysecretpassword
      - database__connection__database=ghost
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__options__host=smtp.mailgun.org
      - mail__options__port=587
      - mail__options__auth__user=postmaster@mydomain.com
      - mail__options__auth__pass=smtpmailgunpassword
    volumes:
      - ./content:/var/lib/ghost/content:Z
    networks:
      - main-network

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=ghost
    volumes:
      - ./mysql_data:/var/lib/mysql:Z
    networks:
      - main-network

  sveltekit:
    container_name: sveltekit
    build: sveltekit/
    restart: unless-stopped
    ports:
      - 5001:5001
    networks:
      - main-network

networks:
  main-network:
    attachable: true
    name: daurialife